export const PATIENT_RECENTLIST_REQUEST = 'PATIENT_RECENTLIST_REQUEST';
export const PATIENT_COMPLETELIST_REQUEST = 'PATIENT_COMPLETELIST_REQUEST';
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS';
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL';

export const FETCH_PATIENTS = 'FETCH_PATIENTS';